version: '3'

services:
  console: &rails
    build:
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RAILS_MAX_THREADS=1
      - WEB_CONCURRENCY=1
    entrypoint: /app/wait_for_db.sh
    volumes:
      - .:/app
    command: ["bash"]
    links:
      - db

  web:
    <<: *rails
    ports:
      - "3000:3000"
    command: ["rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "3333:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
